### ISSUE TITLE
Creating the patch fails silently

### ISSUE THREAD

**Issue by demondzeta** [city41/pb-dino-hack#1]
Hey, first I want to thank you for the time and effort you put in all of your tutorials about neo-geo, I-m trying to follow along in this part and everything goes well until I try to do the actual patch, which fails silently
![image](https://github.com/city41/pb-dino-hack/assets/3608975/5dfb0685-bc8e-4a44-aea6-d63fe05a40cd)

**Comment by demondzeta** [comment]
Also, the only thing that is changed is the address I m trying to use to patch the new image (I tried to use the default images of the project though I followed all the previous steps, to make sure everything is working and is not because I messed up in some place), I selected 9a00 instead of 9c00 though I-m not sure what an empty space entices (is it the ones with zeroes or the one with 15s?? or both ??) anyways, I tried the value you suggested (9c00), the value with 15s (9a00) and one with zeroes (9aff) to see if the problem was the rom i used didn't have the same empty spaces you picked in yours
![image](https://github.com/city41/pb-dino-hack/assets/3608975/e20af3e7-e305-4fd6-9309-b2ff15d2171f)

**Comment by city41** [comment]
Is the tile screenshot from before or after the hack was done?

What do you see when the game is running? Do you see blank or garbage tiles in place of the dino's speech bubble?

> I-m not sure what an empty space entices (is it the ones with zeroes or the one with 15s?? or both ??)

Really it's just whatever tiles the game isn't using. If they are blank (all zeros or all 15s), that's a good sign they aren't used, but it's always possible the game will use them anyway. A lot of this is trial and error.

**Comment by city41** [comment]
Hmmm, it is working for me both at `9c00` and `9a00`. What made you conclude it fails silently? What do you see when the game is running?

Here is what I see after I do the hack


https://github.com/city41/pb-dino-hack/assets/141159/dc3b4c98-ec8c-4daa-a3c3-a3a743391b86

**Comment by city41** [comment]
oh and here is what I see in the tile viewer after the hack 

![image](https://github.com/city41/pb-dino-hack/assets/141159/1359fd0d-74ce-4b70-a56d-d314d7490280)

**Comment by demondzeta** [comment]
> Hmmm, it is working for me both at `9c00` and `9a00`. What made you conclude it fails silently? What do you see when the game is running?
> 
> Here is what I see after I do the hack
> 
this part right here never appears on my console:
![image](https://github.com/city41/pb-dino-hack/assets/3608975/610bf82b-3693-4d54-b4c6-c0f5a77ec579)
I'm really excited by this tutorial so I'm gonna try and do it all over again, but I'm running the yarn command (having changed nothing in the code)
![image](https://github.com/city41/pb-dino-hack/assets/3608975/48c221f8-e316-425b-9fbb-b5c5f726e0c5)
and here you see nothing else happens (the zip part is never shown):
![image](https://github.com/city41/pb-dino-hack/assets/3608975/40127c64-58f4-4233-bf97-2b2e0cb48bae)
I have the pbobblen.zip in the root of the project
![image](https://github.com/city41/pb-dino-hack/assets/3608975/b8049b73-3af0-41b0-9312-fddd3477b8da)
nothing happens in the game
![image](https://github.com/city41/pb-dino-hack/assets/3608975/78662430-5223-4374-84c0-25cc8d046a98)
I  will appreciate any suggestions, and thank you for answering

**Comment by city41** [comment]
ahhh, ok. the script is most likely swallowing an error. These scripts are ummmm, pretty raw :) 

I'll see about fixing the script to always output all the errors it gets, and then when it does it should be more obvious what is failing for you.

**Comment by city41** [comment]
I just pushed out a change to `main.ts` that I think will help. Can you try again? This time it should still fail, but hopefully also output some error info.

**Comment by demondzeta** [comment]
ok imma document my process here, first thing i do yarn install in the root of the repo and this is th e result:
![image](https://github.com/city41/pb-dino-hack/assets/3608975/a4adf6e1-18ba-46bc-b21c-0b3ccfbdef8a)
then I go inside the folder clownassembler and use make there, this is the output:
![image](https://github.com/city41/pb-dino-hack/assets/3608975/b141813d-bf4b-48d6-97ee-0a74500c9da1)
but then i try to do clownassembler/clownassembler and fails :+1: 
![image](https://github.com/city41/pb-dino-hack/assets/3608975/b405c531-75a0-429e-85c9-acaf9edb9b74)
https://github.com/Clownacy/clownassembler suggest to do make assemblers instead:
![image](https://github.com/city41/pb-dino-hack/assets/3608975/c52fe8fa-37cc-4f40-8cb5-3bf0c59b485a)
it seems to work, but lots of warnings. 
now I go back:
![image](https://github.com/city41/pb-dino-hack/assets/3608975/fbf98471-cbfd-41b6-9740-e14a37f960eb)
after copying the rom in the project'sroot
![image](https://github.com/city41/pb-dino-hack/assets/3608975/407ef69f-0195-4b5c-80e8-14dd41862042)
skip to the last part as i have already done the other steps before:
![image](https://github.com/city41/pb-dino-hack/assets/3608975/254ffc81-1cc2-4244-804e-91cd848d2217)
![image](https://github.com/city41/pb-dino-hack/assets/3608975/adc65b88-0d86-419b-b918-bdfaa5b245d2)

this time it seems to work?
but not really :( 
![image](https://github.com/city41/pb-dino-hack/assets/3608975/8eac1331-b224-4656-98c6-891fd07e79e9)
wait... it did??!!
![image](https://github.com/city41/pb-dino-hack/assets/3608975/4d40d691-f354-474b-8d60-3b58ff40e22e)
sorry this time I checked the rom that was in my project's root, and the one that ends up changed is the one in the mame/roms dir
![image](https://github.com/city41/pb-dino-hack/assets/3608975/c9117693-8bac-4a50-879c-676fd55df084)
I don't know what changed but now is working yaehhh!! :). 
Thank you. I documented everything here to see if something helps, I'm learning a lot from you, thank you again for your time. Have a beautiful day

**Comment by city41** [comment]
doh, I'm actually kinda sad it worked :) I was hoping to see some error output. Yeah I dunno what happened. 

Honestly this whole toolchain is held together with duct tape. It could be a *lot* better.

**Comment by demondzeta** [comment]
> doh, I'm actually kinda sad it worked :) I was hoping to see some error output. Yeah I dunno what happened.
> 
> Honestly this whole toolchain is held together with duct tape. It could be a _lot_ better.

I'm just starting to learn, my real objective is to help some friends make a romhack for kof 02, and my ultimate personal goal is to build  an AI for the CPU  in kof 98, something like the shadow system implemented for Killer Instinct(2013), this is a dream I've had for years now and thanks to your tutorial I'm just starting to think it might be possible (information about this has been really cryptic to me honestly). If there's anything I can help you with to improve on these tools please let me know. I might suggest something with time while I' get to learn how things work. Please bear with me if I bother you with some other issue in the future. I'll do it only if I get into a dead end, as you are probably tired of all this at the moment.  I love everything you did here and with the kof 94 project. Thanks again.

**Comment by demondzeta** [comment]
> doh, I'm actually kinda sad it worked :) I was hoping to see some error output. Yeah I dunno what happened.
> 
> Honestly this whole toolchain is held together with duct tape. It could be a _lot_ better.

Hi, I just wanted to add that when I tried part 3 https://github.com/city41/pb-backwards-controls-hack things also failed (changes where not shown, because I had a copy at ..mame/roms/pbobblen.zip already, once i deleted it and tried again it worked, may be something obvious that i couldn't understand before because I'm not a linux guy
